services:
  app:
    image: 302408144168.dkr.ecr.us-west-2.amazonaws.com/kota-hr-myapp-py
    command: sh -c "sleep 10s ; python3 ./Services/main.py"
    depends_on:
      - mysql
    ports:
      - '5002:5000'
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=VroomMustang2000!
    ports:
      - '3306:3306'
